### PR TITLE
WIP: Migrate from Reagent to Rum

### PR DESCRIPTION
**Pull request by ghost**
- [x] Show figures while being dragged
- [x] Avoid performance regression

### CODE REVIEW

**Comment by dialelo** [comment]
Not ready yet, don't merge plz.

**Comment by ghost** [comment]
@jespino take a look please!

**Comment by Alotor** [comment]
WTF!! :open_mouth:

**Comment by jespino** [comment]
The figures aren't showing the "drawing" figure. You can reproduce it, going to the workspace, selecting the rect, and click 1 time in the canvas, move the mouse, click another time. Then appears the rectangle, but between the first click and the second click must appear a rectangle showing you what are you drawing.

**Comment by jespino** [comment]
Works a lot less fluent than the reagent implementation. :disappointed: For example on moving shapes, or updating the pointer position.

**Comment by ghost** [comment]
Noted, thanks for reviewing. Will work on those two things.

**Comment by ghost** [comment]
I consider this ready :shipit:

**Pull request merged**
